### PR TITLE
Add support for expected objects to roundtrip test

### PR DESCRIPTION
**Pull request by overhacked**
Add optional support to test the deserialized bytes against an expected static object. Uses a macro to concisely list modules that contain an `expected()` function that returns the expected `Request` or `Response` object.

Existing tests could have expected objects added to improve the error reporting in case of test failure. Tests from the `proto::message` module have been moved to `tests/roundtrip` because they were simply round-trip tests with an additional check against an expected object.

### CODE REVIEW

**Comment by overhacked** [comment]
Something weird here. I've run `fmt` twice and CI keeps failing on `fmt --check`. Will investigate today.

**Comment by wiktor-k** [comment]
You need a nightly formatter: `cargo +nightly fmt` for import reordering.

**Comment by overhacked** [comment]
🙃 I have been running `cargo +nightly fmt`, but I ran into a `rustfmt` bug, I think. I 1) ran `fmt`, 2) `commit --amend` the changes, then 3) `push`. CI `fmt --check` failed, and I discovered that if I ran `cargo +nightly fmt` **again** on the code I had committed, it had additional lints applied.

In this case, I had multiple trailing blank lines in a doc comment, and it was only stripping them off one line at a time. The next force-push I make should pass `fmt --check`.

**Comment by overhacked** [comment]
> I ran into a `rustfmt` bug, I think.

Turned out to be true and submitted a fix: https://github.com/rust-lang/rustfmt/pull/6163

**Comment by wiktor-k** [comment]
Wow, crazy! I didn't have time to look deeper in the code but it's cool that you've found a bug and submitted a fix PR 👏

**Comment by jcspencer** [comment]
These look great! Once this is merged I'm happy to go back and implement the same for the OpenSSH extensions we have built in, as they also implement their own roundtrip test logic; much nicer to make it more unified!

**Comment by overhacked** [comment]
Just broke this PR up into two separate commits to, hopefully, make it easier to review:

* The first commit contains the changes to `tests/roundtrip` infrastructure to support checking the deserialized object against an expected, statically-constructed object.
* The second commit is the conversion of `proto::message` unit tests to `roundtrip` tests, utilizing the new expected object support.
* (The third commit is a documentation fix to the first commit.)

**Comment by wiktor-k** [comment]
Okay, I've read it. I didn't expect it but it's an clever solution and the line-count is good so let's go ahead and merge it :tada: 

Could you rebase on top of `main`? (If there are any conflicts it's because of my PRs and I'm happy to help resolve  :sweat_smile: )

**Comment by overhacked** [comment]
Rebased onto `main`; should be good to go!

**Review by wiktor-k — APPROVED** [review]
Great! Thank you! 🙇‍♂️

**Pull request merged**
