### PR TITLE
WIP: Migrate to Tokio 1.0

### PR DESCRIPTION
**Pull request by wiktor-k**
This does not compile yet :(

### CODE REVIEW

**Comment by bbigras** [comment]
@wiktor-k btw, your repo doesn't accept issues.

**Comment by wiktor-k** [comment]
🤦‍♂️ Whoops, I guess what was the default after a fork. They're enabled now. Thanks!

**Comment by baloo** [comment]
I think I can take this one off your hands. I reimplemented in my downstream crate.

**Comment by wiktor-k** [comment]
Superseded by #10.

**Pull request closed without merging**
