### PR TITLE
Make error implement std::io::Error and remove associated Agent's Error type

### PR DESCRIPTION
**Pull request by wiktor-k**

### CODE REVIEW

**Comment by wiktor-k** [comment]
I'm wondering what do you think about it @baloo?

I'm on the edge to completely remove `AgentError` and just stick `std::io::Error` in there. The exact error is irrelevant anyway since it's swallowed by `tokio::spawn` and IO Error has some facilities for storing "foreign" errors via `Other` variant :thinking:

**Comment by baloo** [comment]
I might want to revisit error in #16. I don't know yet. Can we hold off on this?

**Comment by wiktor-k** [comment]
> I might want to revisit error in #16. I don't know yet. Can we hold off on this?

As far as I know we don't have any deadlines here 😏 😉

**Comment by wiktor-k** [comment]
BTW thanks for all your contributions. This crate was in dire need of maintenance but I just never had time to do it properly. Thanks! 🙏

**Review by baloo — APPROVED** [review]
I can use the content of #17 and we can always revisit this PR later

**Comment by wiktor-k** [comment]
Okay, thanks! I was just looking at how to merge #17 back without this but didn't get anywhere :)

**Comment by wiktor-k** [comment]
I've also checked #16 and I think it won't be that hard to rebase... the only thing is adding Display match arms to new errors but it should be mostly straightforward.

**Pull request merged**
